### ISSUE TITLE
Erreur d'envoi mail dans SPIP

### ISSUE THREAD

**Issue by Norbert73** [AntoineCabrol/antenneFFMC#20]
Présent sur quelques sites. Exemple ffmc69

---
Suivi :
@Norbert73 ?

**Comment by Norbert73** [comment]
Test avec un message de plus de dix caractères. Avec un temps d'attente avant confirmation. Le 1ier envoi est en erreur mais le second envoi fonctionne bien ?! Ceci est vrai sur 73 et 35.
Par contre l'erreur est systématique sur 69.

**Comment by Norbert73** [comment]
Vérifier si la méthode d'envoi est la même que celle du formulaire point noir.

**Comment by Norbert73** [comment]
Le plugin Facteur 4.0.4 a été installé et paramétré avec succès sur les sites 73,89,84

**Comment by AntoineCabrol** [comment]
@Norbert73, sachant qu'il ne s'agit pas de développement propre au thème mais de configuration du plugin Facteur, cette issue peut être fermée. Je te laisse au préalable renseigner le temps passé, dans la section **_Suivi_** que j'ai ajouté à la description du ticket. Merci !
